# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI-Enclosure
version:      1.02
version_from: Enclosure.pm
installdirs:  site
requires:
    XML::RAI:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
