# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-MyPassword
version:      1.02
version_from: lib/DBIx/MyPassword.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    File::Spec:                    0
    IO::File:                      0
    Text::CSV:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
